### ISSUE TITLE
Set up a repository

### ISSUE THREAD

**Issue by bmind12** [event-maker-telegram-bot/event-maker-telegram-bot#1]
- [x] init repo with `package.json`
- [x] install and configure `typescript`
- [x] install and configure `eslint`
- [x] install and configure `prettier`
- [x] install and configure `express`
- [x] install and configure `rollup` [babel]
- [x] install [commitizen](https://dev.to/amalv/how-to-setup-semantic-release-for-a-react-app-or-a-next-js-app-25c1)

**Comment by bmind12** [comment]
I suggest using webpack over Rollup for the following reason:

> I had a hard time using Rollup for bundling my app that used axios, a very commonly used library for making HTTP requests — not just axios, but for other third-party integrations too. I had to research a lot and try installing many Rollup plugins before attaining victory — at the cost of dropping some imports.

[source](https://medium.com/better-programming/the-battle-of-bundlers-6333a4e3eda9)

Yes, we cannot rely 100% on that conclusion, but I don't won't to find it out when we have a bigger project. But generally I would expect that webpack ecosystem is more mature and there are less issues and better documentation.

Although Rollup is better at tree shacking, it's not the killer feature for the Node.js app, as its size doesn't really matter. Another advantage of Rollup is build time, it's 7 times faster than webpack.
[source1](https://medium.com/js-imaginea/comparing-bundlers-webpack-rollup-parcel-f8f5dc609cfd), [source2](https://x-team.com/blog/rollup-webpack-parcel-comparison/)

Please let me know what you think and I'll proceed with the issue.

**Comment by bmind12** [comment]
@fidelman please take a look ☝️

**Comment by fidelman** [comment]
ahoj @bmind12 , thank you for the research. As I understand from your messages you are not 100% sure which tool to use. I would personally choose Rollup, because:
- As we agreed we develop this project for educational reason, so we can try something new (we use webpack in our work)
- as you mentioned the rollup building time is faster
- We do not need the tree shacking

**Comment by bmind12** [comment]
Hi @fidelman, in the first sentence I said I'd prefer using webpack over rollup and put a reasoning below. But I wanted to ask what do you want to use. So if you want to try something new, we may use rollup, it's not crucial for me. I'll add rollup then and create a pr.

**Comment by bmind12** [comment]
Not sure why PR wasn't linked automatically

**Comment by bmind12** [comment]
I manually linked the PR, it's still `In Progress` though. Maybe it would automatically move to done when we merge `develop` into `master`, maybe

**Comment by fidelman** [comment]
@bmind12 shall we close it?

**Comment by bmind12** [comment]
@fidelman I hoped that when we merge `develop` into `master` it would close automatically, but I think this doesn't work either, so I'm closing it manually
