### ISSUE TITLE
Create a bot with BotFather

### ISSUE THREAD

**Issue by bmind12** [event-maker-telegram-bot/event-maker-telegram-bot#11]
Using your own Telegram account, interact with BotFather telegram bot to create a new bot, get

**Todos:**
- Create a new bot with BotFather bot
- Get an api key to connect and put it into the project (there should be an `.env` file or something similar to manage environmental variables).
- **Don't commit this api key!**
- Interact with BotFather to set up the bot (add needed commands, etc)

**Dev note:**
- Official [documentation](https://core.telegram.org/bots#6-botfather) on BotFather

**Comment by fidelman** [comment]
> Get an api key to connect and put it into the project (there should be an .env file or something similar to manage environmental variables)

I think we will cover it in #8 but for dev .env file is enough

**Comment by bmind12** [comment]
Yes, when deploying yes, there'll be a global vars setup.

**Comment by bmind12** [comment]
The bot was created: @event_maker_telegram_bot
The `/create` command was set up
