### ISSUE TITLE
Bot welcome message

### ISSUE THREAD

**Issue by bmind12** [event-maker-telegram-bot/event-maker-telegram-bot#12]
Implement a bot welcome message to greet new users, and tell about a purpose of the bot. The message should be the following (we may change it if needed, lets discuss in the comments below):

> Hello, {username}!
I am an event-maker Bot 🤖🎈I'll help you to create a calendar event which you may add to any calendar and easily share with friends! 😍
Click `Create a new event` button or send me a `/create` Command! 😊
Please note, I don't store and misuse any provided data 🔒

**Comment by fidelman** [comment]
@bmind12 I think we have to mention that we do not store any user data about the event

**Comment by bmind12** [comment]
@fidelman, agree. How about this:

> Hello, {username}!
I am an event-maker Bot 🤖🎈I'll help you to create a calendar event which you may add to any calendar and easily share with friends! 😍
Click Create new event command to start super simple event wizard 🤹‍♂️
Please note, I don't store and misuse any provided data 🔒

What do you think about the mood of it, about emojis?

**Comment by fidelman** [comment]
@bmind12 I like it! But maybe `super simple event wizard` is too much ?

**Comment by bmind12** [comment]
@fidelman, sure, please make all the corrections and introduce the final version.

**Comment by fidelman** [comment]
> @fidelman, sure, please make all the corrections and introduce the final version.

Hello, {username}!
I am an event-maker Bot 🤖🎈I'll help you to create a calendar event which you may add to any calendar and easily share with friends! 😍
Click `Create a new event` button or send me a `/create` Command! 😊
Please note, I don't store and misuse any provided data 🔒

PS. Just updated `Click Create new event command to start super simple event wizard 🤹‍♂️` using the same patter as in #14

**Comment by bmind12** [comment]
@fidelman, ok, I updated the issue description
