### ISSUE TITLE
Configure CI/CD

### ISSUE THREAD

**Issue by bmind12** [event-maker-telegram-bot/event-maker-telegram-bot#2]
- [x] Install Azure pipelines
- [x] Add linter check
- [x] Add Build badge to Readme

_**Discuss if commit hooks are needed.**_

**Comment by bmind12** [comment]
@fidelman do you want to take this one?

**Comment by fidelman** [comment]
@bmind12 do not you mind if I try [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)?

**Comment by bmind12** [comment]
> @bmind12 do not you mind if I try [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)?

Sure, go ahead.
