### ISSUE TITLE
Configure branches protection

### ISSUE THREAD

**Issue by bmind12** [event-maker-telegram-bot/event-maker-telegram-bot#4]
Configure branches protection so that no direct pushes allowed. Any new code should be added via PR, only when approved by another contributor and CI pipeline is passed.

TBD: what branches to protect and how.

**Comment by bmind12** [comment]
I set up the protection for `master` and `develop` branches, please take a look in the project settings if you have right to see it. If not, then we find another way to check it.

**Comment by fidelman** [comment]
ahoj @bmind12 , I cannot see the settings, but I've just checked and I am not able to strictly push to `master` and `develop`. So I close this issue. Thanks
