### ISSUE TITLE
Implement development server

### ISSUE THREAD

**Issue by bmind12** [event-maker-telegram-bot/event-maker-telegram-bot#7]
We need to choose, install and add a script to run a development server.

At first glance it seems there is no specific and commonly used package, please check discussion here: https://github.com/rollup/rollup/issues/2385

**Comment by fidelman** [comment]
thank you creating this issue and for the discussion link. Will double check it later.
For my first glance I found this plugin https://github.com/rollup/plugins/tree/master/packages/run which might be helpful
